INSERT INTO ucode_web.heroes (name, description, class_role)
VALUES ('Iron Man', 'Anthony "Tony" Stark is a genius inventor and billionaire industrialist, who suits up in his armor of cutting-edge technology to become the super hero Iron Man. The adopted son of weapons manufacturer Howard Stark,[50] Tony inherited his family''s company at a young age following his parents'' death.[51] While overseeing a manufacturing plant in a foreign country, Stark was kidnapped by local terrorists. Instead of giving in to his captors'' demands to build weapons for them, Stark created a powerful suit of armor for himself to escape.[52] Returning to America, Stark further upgraded the armor and put his vast resources and intellect to use for the betterment of the world as Iron Man.', 'tankman');

INSERT INTO ucode_web.heroes (name, description, class_role)
VALUES ('Black Widow', 'A former KGB agent, Natalia Romanova otherwise known as Black Widow defected to the United States from the Soviet Union (later known as Russia) to join S.H.I.E.L.D.. Later Black Widow would then become a member of the Avengers and has been on the team on multiple occasions. She is a woman with a mysterious past few know about.', 'dps');

INSERT INTO ucode_web.heroes (name, description, class_role)
VALUES ('Captain Marvel', 'For a long period of time, two alien races, the Kree and the Skrull, have been in constant warfare with each other. As the Kree are the ultimately superior species due to their technological advancements, the Skrulls have been numbered significantly, on the verge of extinction. The Kree Empire continues to attempt to wipe the Skrulls off the face of the galaxy. In 1995, at the height of the war, Vers resides in Hala.', 'dps');

INSERT INTO ucode_web.heroes (name, description, class_role)
VALUES ('Antmen', 'The Ant Men are the last survivors of the Microverse. The realm was attacked by its long time foe the Psycho-Man, who used his Emotocaster to drive the entire planet insane. The group''s leader is Marionette who succumbed to the madness and killed her husband Arcturus Rann. The remaining members of the Microns would soon realize that they would not attack each other as long as they didn''t look at each other. They would then take their cable car and tried to escape the Microverse. They would arrive just as Man-Thing came to plug up the portal in HEL Laboratories to prevent the Psycho-Man''s madness to seep out into our reality.', 'healer');

INSERT INTO ucode_web.heroes (name, description, class_role)
VALUES ('Star-lord', 'For many years, Terran-born Peter Quill has been traveling space, saving aliens, fighting wars and protecting the innocent from the evil of outer space using the moniker of Star-Lord. Even after Quill left behind the name because of a tragic event that resulted in the loss of many lives, the name and legend of the Star-Lord perdured. Today, the legend is still alive and being told everywhere from the corners of the Kree Empire to the limits of the known universe.', 'healer');

INSERT INTO ucode_web.heroes (name, description, class_role)
VALUES ('Daredevil', 'The son of boxer Battlin'' Jack, Matt Murdock grew up in the relative poverty of Hell''s Kitchen with much reverence for his father, who constantly pressed him to study instead of playing with his friends. In turn, they taunted him with the nickname Daredevil since he always went back to studying and secretly training in his father''s gym instead of doing things with them.', 'healer');

INSERT INTO ucode_web.heroes (name, description, class_role)
VALUES ('Punisher', 'A war veteran, Frank Castle became a vigilante after seeing his wife and children gunned down for accidentally observing a Mafia "hit". Since then, he has devoted his life to the task of destroying organized crime wherever he finds it. Although he aids many heroes in their quests, they often come into conflict over his way of dealing with crime. At first, the Punisher was conceived by his creator, Gerry Conway, as a potential recurring antagonist for Spider-Man; however, his 1974 debut was critically acclaimed, and he became an anti-hero in the Marvel universe and an uneasy ally of The Wall Crawler. Throughout the years, the Punisher has appeared in the books of other Marvel heroes, such as Captain America, Daredevil, Ghost Rider, and many more.', 'healer');

INSERT INTO ucode_web.heroes (name, description, class_role)
VALUES ('T''Challa', 'T''Challa aka the Black Panther[22] is the head of state for the African nation of Wakanda, the most technologically advanced country on Earth. In this role, he was the King/Chieftain, religious leader, and commander-in-chief all rolled into one.[23] He was also considered among the top intellects in the world.[24] Using Wakanda''s advanced Vibranium technology and his own abilities and fortune, he pledged his life to the service of all humankind.', 'healer');

INSERT INTO ucode_web.heroes (name, description, race, class_role)
VALUES ('Thor', 'Leaping from the legends of Norse mythology, the Asgardian God of Thunder, Thor Odinson, is the son of Odin the All-Father and Jord, Elder Goddess and spirit of the Earth. He frequently stands alongside the Avengers in the defense of the people of Midgard (Earth), often against the schemes of his adopted brother Loki. He formerly dwelt in a recreation of Asgard in Oklahoma, using the mortal form of Donald Blake to provide a bridge between his people and the mortals surrounding them. However, Loki''s subtle trickery and manipulations of Balder, combined with her time-twisting of Asgard''s past and that of Bor and Odin''s has enabled her to banish Thor from Asgard, stripping him of his titles, throne and legal power, and move his people to Doctor Doom''s Latveria, having planned this ever since her rebirth. Thor returned to Asgard, just in time to aid them in a battle against Norman Osborn''s Dark Avengers, X-Men, and H.A.M.M.E.R., killing Sentry after he destroyed Asgard. Feeling lonely, Thor has resurrected his brother Loki and father Odin and they continue to battle-on for the survival of Asgard.', 'avenger', 'tankman');

INSERT INTO ucode_web.heroes (name, description, class_role)
VALUES ('Vision', 'The Vision is a "synthezoid," an advanced android, built to replicate the human form using Horton Cells,[4] with the Solar Gem to give him consciousness.[5] He was constructed by Ultron using parts of the original Human Torch which was created by Phineas Horton.[6] He was later modified using brain patterns partially based on those of Wonder Man[7] and then Alex Lipton.[8] He turned on his creator and joined the Avengers, becoming one of its leading members.', 'healer');

INSERT INTO ucode_web.heroes (name, description, race, class_role)
VALUES ('Gomora', 'Gamora is the last of her species, a race called the Zen-Whoberis who were all slaughtered by the Universal Church of Truth. She was later found by the Mad Titan Thanos, who raised her as his daughter as well as an assassin to carry out his deeds. Eventually, Gamora would join a group of intergalactic misfits known as the Guardians of the Galaxy, becoming a prominent member of the group.', 'monster', 'healer');

